const STORAGE_KEY='ellens-project-v2';
const ex=(id,name,sets,reps,weight,target,instructions,search)=>({id,name,sets,reps,weight,done:false,target,instructions,youtube:'',search});
const weeklyPlan={
  0:{name:'Recovery & Mobility',exercises:[ex('sun-walk','Recovery Walk',1,30,0,'Cardiovascular recovery','Walk at an easy pace. Keep your breathing relaxed.','recovery walk workout'),ex('sun-mobility','Full Body Mobility',1,15,0,'Hips · Shoulders · Spine','Move slowly through a comfortable range. Do not force painful positions.','15 minute full body mobility')]},
  1:{name:'Lower Body + Core',exercises:[ex('mon-squat','Barbell Squat',4,8,40,'Quadriceps · Glutes · Core','Brace your core, keep the whole foot grounded, and drive up with control.','barbell squat proper form'),ex('mon-rdl','Romanian Deadlift',4,10,30,'Hamstrings · Glutes · Back','Push the hips back with a neutral spine and keep the bar close to your legs.','romanian deadlift proper form'),ex('mon-lunge','Reverse Lunge',3,10,0,'Glutes · Quadriceps','Step back softly and keep the front knee tracking over the foot.','reverse lunge proper form'),ex('mon-hip','Hip Thrust',4,12,40,'Glutes · Hamstrings','Tuck the ribs, drive through the heels, and pause at full hip extension.','barbell hip thrust proper form'),ex('mon-plank','Plank',3,45,0,'Core · Shoulders','Keep a straight line from head to heels and breathe steadily.','plank proper form')]},
  2:{name:'Upper Body Push',exercises:[ex('tue-bench','Bench Press',4,8,20,'Chest · Triceps · Shoulders','Keep shoulder blades set, feet planted, and lower the bar with control.','bench press proper form'),ex('tue-press','Dumbbell Shoulder Press',3,10,8,'Shoulders · Triceps','Keep ribs down and press without shrugging.','dumbbell shoulder press form'),ex('tue-incline','Incline Dumbbell Press',3,10,8,'Upper Chest · Triceps','Use a low incline and keep wrists stacked over elbows.','incline dumbbell press form'),ex('tue-raise','Lateral Raise',3,15,4,'Side Deltoids','Lift with soft elbows and stop near shoulder height.','dumbbell lateral raise proper form'),ex('tue-triceps','Cable Triceps Pushdown',3,12,15,'Triceps','Keep elbows beside your torso and fully extend without swinging.','cable triceps pushdown form')]},
  3:{name:'Run + Mobility',exercises:[ex('wed-run','Easy Run',1,30,0,'Cardiovascular endurance','Stay at a conversational pace and finish with easy walking.','easy running form beginner'),ex('wed-strides','Running Strides',6,20,0,'Running technique · Speed','Accelerate smoothly, stay relaxed, and walk back to recover.','running strides technique'),ex('wed-mobility','Hip & Ankle Mobility',1,12,0,'Hips · Ankles','Use controlled movements and stay within a pain-free range.','hip ankle mobility routine')]},
  4:{name:'Lower Body Strength',exercises:[ex('thu-deadlift','Deadlift',4,6,40,'Hamstrings · Glutes · Back','Brace before lifting, keep the bar close, and stand tall without leaning back.','deadlift proper form'),ex('thu-goblet','Goblet Squat',3,12,12,'Quadriceps · Glutes · Core','Hold the weight close and sit down between your hips.','goblet squat proper form'),ex('thu-curl','Leg Curl',3,12,20,'Hamstrings','Keep hips down and control both phases of the movement.','seated leg curl proper form'),ex('thu-calf','Standing Calf Raise',4,15,0,'Calves','Use a full range and pause at the top.','standing calf raise proper form'),ex('thu-deadbug','Dead Bug',3,10,0,'Deep Core','Keep the lower back gently pressed down while extending opposite limbs.','dead bug exercise proper form')]},
  5:{name:'Upper Body Pull',exercises:[ex('fri-pulldown','Lat Pulldown',4,10,25,'Lats · Biceps','Pull elbows toward your ribs without leaning far back.','lat pulldown proper form'),ex('fri-row','Seated Cable Row',3,12,25,'Lats · Rhomboids · Biceps','Keep the torso stable, pull elbows back, and return under control.','seated cable row proper form'),ex('fri-face','Face Pull',3,15,10,'Rear Delts · Upper Back','Pull toward eye level and rotate the hands apart.','cable face pull proper form'),ex('fri-curl','Dumbbell Curl',3,12,6,'Biceps','Keep elbows still and avoid swinging.','dumbbell biceps curl form'),ex('fri-carry','Farmer Carry',4,30,12,'Grip · Core · Traps','Walk tall with short controlled steps and steady breathing.','farmer carry proper form')]},
  6:{name:'HYROX / Full Body',exercises:[ex('sat-row','Row Erg',1,1000,0,'Full Body · Cardio','Drive with the legs first, then lean and pull. Recover in reverse order.','rowing machine proper technique'),ex('sat-burpee','Burpee Broad Jump',4,10,0,'Full Body · Cardio','Land softly, keep a steady rhythm, and scale the jump when needed.','burpee broad jump hyrox technique'),ex('sat-carry','Farmer Carry',4,50,16,'Grip · Core · Legs','Keep shoulders down and walk with controlled steps.','farmer carry hyrox technique'),ex('sat-lunge','Walking Lunge',4,20,0,'Glutes · Quadriceps','Stay tall and let the back knee move toward the floor.','walking lunge proper form'),ex('sat-wallball','Wall Ball',4,15,6,'Legs · Shoulders · Cardio','Squat with the ball at chest height and use leg drive to throw.','wall ball proper form')]}
};
const defaults={settings:{name:'Ellen',sex:'female',age:37,height:160,currentWeight:78,currentBodyFat:'',goalWeight:74.5,goalMode:'fatloss',activity:1.55,mealCount:4,waterGoal:2500,sleepGoal:7.5,proteinGoal:125,calorieGoal:1650,carbGoal:165,fatGoal:55},logs:{},body:[],lastCelebrated:{}};
let state=loadState(),activeDate=todayKey(),selectedDate=todayKey(),calendarCursor=new Date(),editingIndex=null,deferredPrompt=null,supabaseClient=null,currentUser=null;
function todayKey(){return new Date().toLocaleDateString('en-CA')}function clone(v){return JSON.parse(JSON.stringify(v))}function dateFromKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)}function keyFromDate(d){return d.toLocaleDateString('en-CA')}function shiftDate(k,n){const d=dateFromKey(k);d.setDate(d.getDate()+n);return keyFromDate(d)}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem('ellens-project-v1')||'{}',parsed=JSON.parse(raw);return {...clone(defaults),...parsed,settings:{...clone(defaults).settings,...(parsed.settings||{})}}}catch{return clone(defaults)}}function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));scheduleCloudSync()}
function plannedExercises(date){return clone(weeklyPlan[dateFromKey(date).getDay()].exercises).map(x=>({...x,id:x.id+'-'+date,done:false}))}
function isLegacyDefaults(list=[]){const names=list.map(x=>x.name).join('|');return names==='Barbell Squat|Seated Cable Row|Easy Run'}
function getLog(date=activeDate){
  if(!state.logs[date]){
    state.logs[date]={priorities:{workout:false,nutrition:false,water:false,sleep:false},water:0,sleep:0,calories:0,protein:0,memo:'',exercises:plannedExercises(date),planInitialized:true,planSource:'weekly',updatedAt:new Date().toISOString()};
  }else{
    const log=state.logs[date];
    log.priorities=log.priorities||{workout:false,nutrition:false,water:false,sleep:false};
    if((!Array.isArray(log.exercises)||log.exercises.length===0||isLegacyDefaults(log.exercises))&&log.planSource!=='custom-empty'){
      log.exercises=plannedExercises(date);log.planInitialized=true;log.planSource='weekly';log.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
    }
  }
  return state.logs[date]
}
function scoreFor(log){const p=log.priorities||{};const vals=[p.workout,p.nutrition,p.water,p.sleep].map(Boolean);return Math.round(vals.filter(Boolean).length/vals.length*100)}
function mood(s){if(s===0)return{emoji:'😔',line:'You can always restart.',title:"Today wasn't your day."};if(s<50)return{emoji:'🙂',line:'A small step is still a step.',title:'Keep moving.'};if(s<75)return{emoji:'😄',line:"You're building momentum.",title:'Halfway there.'};if(s<100)return{emoji:'🔥',line:"You're getting stronger.",title:'Finish what you started.'};return{emoji:'🤖✨',line:'Smile. Train. Become the Machine.',title:'Perfect Day Complete!'}}
const mealChoices={breakfast:['달걀 2개 · 그릭요거트 · 블루베리','오트밀 · 우유 · 바나나 · 달걀','통밀토스트 · 달걀 · 토마토'],lunch:['일반식 · 밥 반 공기 · 단백질 반찬 · 채소','현미밥 · 닭다리살 · 구운채소','포케 · 현미밥 · 연어 · 채소'],snack:['프로틴 음료 · 과일','그릭요거트 · 아몬드 소량','바나나 · 삶은 달걀'],dinner:['닭가슴살 또는 두부 · 샐러드 · 고구마','연어 · 구운채소 · 잡곡밥 소량','소고기 우둔살 · 샐러드 · 감자']};

const FOOD_DB=[
 ['흰쌀밥',210,150,'g',4,46,0.5],['현미밥',218,150,'g',4.5,45,2],['잡곡밥',225,150,'g',5,46,2],['고구마',129,150,'g',2,30,0.2],['오트밀',190,50,'g',6.5,34,3.5],['통밀빵',150,2,'장',6,28,2],
 ['닭가슴살',165,100,'g',31,0,3.6],['닭다리살',190,100,'g',24,0,10],['소고기 우둔살',170,100,'g',27,0,7],['돼지 안심',143,100,'g',26,0,4],['연어',208,100,'g',20,0,13],['흰살생선',120,100,'g',24,0,2],['참치캔(물)',116,100,'g',26,0,1],
 ['삶은 달걀',70,1,'개',6,0.5,5],['두부',80,100,'g',8,2,5],['그릭요거트',120,150,'g',15,8,3],['우유',125,200,'ml',6.5,10,7],['무가당 두유',95,190,'ml',7,4,5],['프로틴 음료',150,1,'병',25,8,2],
 ['바나나',105,1,'개',1.3,27,0.4],['사과',95,1,'개',0.5,25,0.3],['블루베리',57,100,'g',0.7,14,0.3],['아몬드',116,20,'g',4,4,10],['샐러드 채소',35,150,'g',2,7,0.4],['아보카도',160,100,'g',2,9,15],
 ['김치찌개',330,1,'인분',22,18,18],['된장찌개',170,1,'인분',12,18,7],['비빔밥',560,1,'인분',19,88,15],['김밥',480,1,'줄',15,75,14],['닭가슴살 포케',520,1,'인분',38,62,14],['샌드위치',420,1,'개',22,48,15]
].map((x,i)=>({id:'food-'+i,name:x[0],kcal:x[1],serving:x[2],unit:x[3],protein:x[4],carbs:x[5],fat:x[6]}));
let editingMealIndex=null,selectedFood=null;
function mealFoodTotals(meal){return (meal.foodItems||[]).reduce((a,x)=>({kcal:a.kcal+(+x.kcal||0),protein:a.protein+(+x.protein||0),carbs:a.carbs+(+x.carbs||0),fat:a.fat+(+x.fat||0)}),{kcal:0,protein:0,carbs:0,fat:0})}
function dailyFoodTotals(meals){return meals.reduce((a,m)=>{const t=mealFoodTotals(m);return{kcal:a.kcal+t.kcal,protein:a.protein+t.protein,carbs:a.carbs+t.carbs,fat:a.fat+t.fat}},{kcal:0,protein:0,carbs:0,fat:0})}
function roundMacro(n){return Math.round((+n||0)*10)/10}
function syncFoodTotals(log,meals){const t=dailyFoodTotals(meals);if(t.kcal>0){log.calories=Math.round(t.kcal);log.protein=Math.round(t.protein);log.carbs=Math.round(t.carbs);log.fat=Math.round(t.fat)}return t}
function ensureFoodDialog(){if(document.getElementById('foodDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="foodDialog" class="modal food-modal"><button class="close-btn" id="foodDialogClose">×</button><p class="eyebrow">MEAL LOGGER</p><h2 id="foodDialogTitle">음식 검색 및 합계</h2><div class="food-search-row"><input id="foodSearch" placeholder="음식명 검색 (예: 닭가슴살, 비빔밥)"><button class="secondary-btn inline-btn" id="customFoodBtn">직접 영양 입력</button></div><div id="foodResults" class="food-results"></div><div id="foodServingPanel" class="food-serving" hidden><h3 id="selectedFoodName"></h3><div class="form-row"><label>섭취량<input id="foodAmount" type="number" min="0" step="0.1"></label><label>단위<input id="foodUnit" readonly></label></div><p id="foodPreview" class="muted"></p><button class="primary-btn" id="addFoodBtn">이 음식 추가</button></div><div class="section-head"><h2>현재 식사</h2></div><div id="mealFoodList" class="meal-food-list"></div><div id="mealFoodTotal" class="meal-total"></div><button class="primary-btn" id="saveMealFoodsBtn">식단 저장</button></dialog>`);
 foodDialogClose.onclick=()=>foodDialog.close();foodSearch.oninput=renderFoodResults;customFoodBtn.onclick=openCustomFoodPrompt;foodAmount.oninput=renderFoodPreview;addFoodBtn.onclick=addSelectedFood;saveMealFoodsBtn.onclick=saveMealFoods;
}
function openFoodEditor(index){ensureFoodDialog();editingMealIndex=index;selectedFood=null;foodSearch.value='';foodServingPanel.hidden=true;foodDialogTitle.textContent=ensureMeals(getLog(activeDate),activeDate)[index].name+' 음식 기록';renderFoodResults();renderMealFoodList();foodDialog.showModal()}
function renderFoodResults(){const q=(foodSearch?.value||'').trim().toLowerCase();const list=FOOD_DB.filter(x=>!q||x.name.toLowerCase().includes(q)).slice(0,12);foodResults.innerHTML=list.map(x=>`<button class="food-result" data-food-id="${x.id}"><b>${x.name}</b><span>${x.kcal} kcal / ${x.serving}${x.unit}</span></button>`).join('')||'<p class="muted">검색 결과가 없습니다. 직접 영양 입력을 사용하세요.</p>';foodResults.querySelectorAll('[data-food-id]').forEach(b=>b.onclick=()=>selectFood(b.dataset.foodId))}
function selectFood(id){selectedFood=FOOD_DB.find(x=>x.id===id);if(!selectedFood)return;selectedFoodName.textContent=selectedFood.name;foodAmount.value=selectedFood.serving;foodUnit.value=selectedFood.unit;foodServingPanel.hidden=false;renderFoodPreview()}
function renderFoodPreview(){if(!selectedFood)return;const ratio=(+foodAmount.value||0)/selectedFood.serving;foodPreview.textContent=`약 ${Math.round(selectedFood.kcal*ratio)} kcal · P ${roundMacro(selectedFood.protein*ratio)}g · C ${roundMacro(selectedFood.carbs*ratio)}g · F ${roundMacro(selectedFood.fat*ratio)}g`}
function addSelectedFood(){if(!selectedFood||(+foodAmount.value||0)<=0)return;const amount=+foodAmount.value,ratio=amount/selectedFood.serving,m=ensureMeals(getLog(activeDate),activeDate)[editingMealIndex];m.foodItems=m.foodItems||[];m.foodItems.push({name:selectedFood.name,amount,unit:selectedFood.unit,kcal:Math.round(selectedFood.kcal*ratio),protein:roundMacro(selectedFood.protein*ratio),carbs:roundMacro(selectedFood.carbs*ratio),fat:roundMacro(selectedFood.fat*ratio)});renderMealFoodList();selectedFood=null;foodServingPanel.hidden=true}
function openCustomFoodPrompt(){const name=prompt('음식명을 입력하세요.');if(!name)return;const kcal=+prompt('총 칼로리(kcal)를 입력하세요.','0')||0,protein=+prompt('단백질(g)을 입력하세요.','0')||0,carbs=+prompt('탄수화물(g)을 입력하세요.','0')||0,fat=+prompt('지방(g)을 입력하세요.','0')||0,m=ensureMeals(getLog(activeDate),activeDate)[editingMealIndex];m.foodItems=m.foodItems||[];m.foodItems.push({name,amount:1,unit:'회',kcal,protein,carbs,fat});renderMealFoodList()}
function renderMealFoodList(){const m=ensureMeals(getLog(activeDate),activeDate)[editingMealIndex],items=m.foodItems||[];mealFoodList.innerHTML=items.map((x,i)=>`<div class="meal-food-row"><div><b>${escapeHtml(x.name)}</b><small>${x.amount}${escapeHtml(x.unit)} · ${x.kcal} kcal · P ${x.protein}g</small></div><button class="mini-edit" data-remove-food="${i}">삭제</button></div>`).join('')||'<p class="muted">아직 추가한 음식이 없습니다.</p>';mealFoodList.querySelectorAll('[data-remove-food]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.removeFood,1);renderMealFoodList()});const t=mealFoodTotals(m);mealFoodTotal.innerHTML=`<strong>${Math.round(t.kcal)} kcal</strong><span>P ${roundMacro(t.protein)}g · C ${roundMacro(t.carbs)}g · F ${roundMacro(t.fat)}g</span>`}
function saveMealFoods(){const l=getLog(activeDate),meals=ensureMeals(l,activeDate),m=meals[editingMealIndex];if((m.foodItems||[]).length){m.customText=m.foodItems.map(x=>x.name).join(' · ')}else delete m.customText;syncFoodTotals(l,meals);l.updatedAt=new Date().toISOString();saveState();foodDialog.close();render()}

function calculateNutrition(){const s=state.settings,w=+s.currentWeight||78,h=+s.height||160,age=+s.age||37,sex=s.sex||'female',act=+s.activity||1.55;let bmr=10*w+6.25*h-5*age+(sex==='male'?5:-161),tdee=bmr*act,delta={loss:-500,fatloss:-400,maintain:0,gain:250,hyrox:-150,manual:0}[s.goalMode]??-400;let kcal=s.goalMode==='manual'?(+s.calorieGoal||1800):Math.round((tdee+delta)/50)*50;const floor=sex==='male'?1500:1200;kcal=Math.max(floor,kcal);let protein=Math.round(w*({loss:1.5,fatloss:1.7,maintain:1.5,gain:1.8,hyrox:1.7,manual:(+s.proteinGoal||120)/w}[s.goalMode]||1.6));if(s.goalMode==='manual')protein=+s.proteinGoal||120;let fat=Math.round(w*.7),carb=Math.max(80,Math.round((kcal-protein*4-fat*9)/4));return{bmr:Math.round(bmr),tdee:Math.round(tdee),kcal,protein,carb,fat,water:Math.round(w*30/250)*250}}
function ensureMeals(log,date){if(!log.mealPlan||!Array.isArray(log.mealPlan)){const count=+state.settings.mealCount||4,keys=count===3?['breakfast','lunch','dinner']:['breakfast','lunch','snack','dinner'];log.mealPlan=keys.map((key,i)=>({key,name:{breakfast:'Breakfast',lunch:'Lunch',snack:'Snack',dinner:'Dinner'}[key],choice:i%mealChoices[key].length,done:false}));log.updatedAt=new Date().toISOString()}return log.mealPlan}
function renderMeals(log){const t=calculateNutrition(),meals=ensureMeals(log,activeDate),eaten=syncFoodTotals(log,meals);nutritionTargetCard.innerHTML=`<div><p class="eyebrow">DAILY NUTRITION</p><h3>${Math.round(eaten.kcal).toLocaleString()} / ${t.kcal.toLocaleString()} kcal</h3><p class="muted">섭취 P ${roundMacro(eaten.protein)}g · C ${roundMacro(eaten.carbs)}g · F ${roundMacro(eaten.fat)}g</p><p class="muted">목표 P ${t.protein}g · C ${t.carb}g · F ${t.fat}g · Water ${t.water.toLocaleString()}ml</p></div><span class="goal-pill">${escapeHtml(state.settings.goalMode)}</span>`;mealPlanList.innerHTML=meals.map((m,i)=>{const mt=mealFoodTotals(m),text=m.customText||mealChoices[m.key][m.choice%mealChoices[m.key].length],summary=mt.kcal>0?`${Math.round(mt.kcal)} kcal · P ${roundMacro(mt.protein)}g · C ${roundMacro(mt.carbs)}g · F ${roundMacro(mt.fat)}g`:(m.customText?'직접 입력한 식단':Math.round(t.kcal/meals.length)+' kcal guideline');return `<article class="meal-plan-card ${m.done?'done':''}"><button class="meal-check" data-meal-done="${i}" aria-label="Complete meal">${m.done?'✓':'○'}</button><div><p class="eyebrow">${m.name.toUpperCase()}</p><h3>${escapeHtml(text)}</h3><small>${summary}</small></div><div class="meal-actions"><button class="mini-edit" data-meal-food="${i}">음식 검색·합계</button><button class="mini-edit" data-meal-edit="${i}">메모 입력</button><button class="mini-edit" data-meal-change="${i}">추천 변경</button></div></article>`}).join('')}
function updateGreeting(){const h=new Date().getHours(),part=h<12?'morning':h<18?'afternoon':'evening';greeting.textContent=`Good ${part}, ${state.settings.name||'Ellen'}.`}
function render(){updateGreeting();renderToday();renderPlan();renderCalendar();renderProgress();renderSettings()}
function renderPlan(){
  const grid=document.getElementById('weeklyPlanGrid');if(!grid)return;
  const today=new Date(),todayDay=today.getDay(),monday=new Date(today);monday.setDate(today.getDate()-((todayDay+6)%7));
  const order=[1,2,3,4,5,6,0],names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  grid.innerHTML=order.map((day,idx)=>{const dt=new Date(monday);dt.setDate(monday.getDate()+idx);const key=keyFromDate(dt),plan=weeklyPlan[day],isToday=key===todayKey();return `<article class="plan-day-card ${isToday?'today-plan':''}"><div class="plan-day-head"><div><p class="eyebrow">${isToday?'TODAY':names[day].toUpperCase()}</p><h3>${escapeHtml(plan.name)}</h3><p class="muted">${new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(dt)}</p></div><span class="routine-count">${plan.exercises.length} EXERCISES</span></div><div class="plan-exercises">${plan.exercises.map(x=>`<span class="plan-chip">${escapeHtml(x.name)}</span>`).join('')}</div><button class="secondary-btn plan-open-btn" data-open-plan-date="${key}">Open & customise</button></article>`}).join('');
}
function renderToday(){const log=getLog(activeDate);autoPriorities(log);const score=scoreFor(log),m=mood(score),d=dateFromKey(activeDate),isToday=activeDate===todayKey();scoreValue.textContent=`${score}%`;scoreEmoji.textContent=m.emoji;coachLine.textContent=m.line;scoreRing.style.setProperty('--score',score);scoreRing.querySelector('span').textContent=score;workoutDayLabel.textContent=isToday?'TODAY':new Intl.DateTimeFormat('en',{weekday:'long'}).format(d).toUpperCase();workoutDateLabel.textContent=new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(d);routineName.textContent=weeklyPlan[d.getDay()].name;workoutHeading.textContent=isToday?"Today's workout":"Day workout";todayWorkoutBtn.hidden=isToday;renderMeals(log);
 const defs=[['workout','Workout','Complete every exercise','🏋️'],['nutrition','Nutrition','Log calories and protein','🥗'],['water','Water',`${log.water}/${state.settings.waterGoal} ml`,'💧'],['sleep','Sleep',`${log.sleep}/${state.settings.sleepGoal} h`,'🌙']];priorityGrid.innerHTML=defs.map(([k,t,s,e])=>`<button class="priority-card ${log.priorities[k]?'done':''}" data-priority="${k}"><span>${e}</span><b>${t}</b><small>${s}</small></button>`).join('');
 workoutList.innerHTML=log.exercises.length?log.exercises.map((x,i)=>`<article class="exercise-card ${x.done?'done':''}"><input class="check" type="checkbox" data-ex-check="${i}" ${x.done?'checked':''} aria-label="Complete ${escapeHtml(x.name)}"><button class="text-btn exercise-open" data-ex-open="${i}" style="text-align:left"><h3>${escapeHtml(x.name)}</h3><p>${x.sets} sets × ${x.reps} reps${x.weight?` · ${x.weight} kg`:''}</p></button><button class="mini-edit" data-ex-edit="${i}" aria-label="Edit ${escapeHtml(x.name)}">Edit</button></article>`).join(''):'<div class="empty-state"><span>🧘</span><p>No exercises scheduled.</p><button class="text-btn" data-empty-add>+ Add an exercise</button></div>';
 waterInput.value=log.water||'';sleepInput.value=log.sleep||'';calorieInput.value=log.calories||'';proteinInput.value=log.protein||'';memoInput.value=log.memo||'';if(isToday)maybeCelebrate(score)}
function autoPriorities(l){l.priorities=l.priorities||{};l.priorities.workout=l.exercises.length>0&&l.exercises.every(x=>x.done);l.priorities.water=+l.water>=+state.settings.waterGoal;l.priorities.sleep=+l.sleep>=+state.settings.sleepGoal;l.priorities.nutrition=+l.calories>0&&+l.protein>0}
function updateLog(patch,date=activeDate){Object.assign(getLog(date),patch,{updatedAt:new Date().toISOString()});saveState();render()}
function maybeCelebrate(s){const k=todayKey();if(s===100&&state.lastCelebrated[k]!==100){showCelebration(s);state.lastCelebrated[k]=100;saveState()}}
function showCelebration(s){const m=mood(s);celebrationContent.innerHTML=`<div class="big-emoji">${m.emoji}</div><h2>${m.title}</h2><p>${m.line}</p><p class="slogan">Smile. Train. Become the Machine.</p>`;celebrationDialog.showModal();if(s===100)confetti()}
function confetti(){for(let i=0;i<28;i++){const el=document.createElement('i');el.className='confetti';el.style.left=Math.random()*100+'vw';el.style.setProperty('--x',(Math.random()*180-90)+'px');el.style.animationDelay=Math.random()*.5+'s';document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();monthTitle.textContent=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(calendarCursor);const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first.getDay();i++)html+='<div class="day blank"></div>';for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,s=state.logs[key]?scoreFor(state.logs[key]):0;html+=`<button class="day ${key===todayKey()?'today':''} ${key===selectedDate?'selected':''}" data-date="${key}"><span>${d}</span><span>${s===100?'🤖':s===0?'':'•'}</span><span class="heat"><i style="width:${s}%"></i></span></button>`}calendarGrid.innerHTML=html;renderDaySummary()}
function renderDaySummary(){const log=state.logs[selectedDate],s=log?scoreFor(log):0,m=mood(s),routine=weeklyPlan[dateFromKey(selectedDate).getDay()];daySummary.innerHTML=`<p class="eyebrow">${selectedDate}</p><h2>${routine.name}</h2><p class="muted">${m.emoji} ${s}% complete · ${log?.exercises?.length??routine.exercises.length} exercises</p>${log?`<p>Water ${log.water||0} ml · Sleep ${log.sleep||0} h · Protein ${log.protein||0} g</p>`:'<p>The weekly plan will be created when you open this day.</p>'}<button class="primary-btn" id="openSelectedDay">Open this workout</button>`;document.getElementById('openSelectedDay').onclick=()=>{activeDate=selectedDate;switchView('today');renderToday()}}
function renderProgress(){const keys=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return keyFromDate(d)});weeklyBars.innerHTML=keys.map(k=>{const s=state.logs[k]?scoreFor(state.logs[k]):0;return`<div class="bar-col"><div class="bar" style="height:${Math.max(s,2)}%"></div><small>${k.slice(8)}</small></div>`}).join('')}
function renderSettings(){const s=state.settings;displayName.value=s.name||'Ellen';sexSetting.value=s.sex||'female';ageSetting.value=s.age||37;heightSetting.value=s.height||160;currentWeightSetting.value=s.currentWeight||'';currentBodyFatSetting.value=s.currentBodyFat||'';goalWeightSetting.value=s.goalWeight||'';goalMode.value=s.goalMode||'fatloss';activitySetting.value=String(s.activity||1.55);mealCountSetting.value=String(s.mealCount||4);waterGoal.value=s.waterGoal;sleepGoal.value=s.sleepGoal;proteinGoal.value=s.proteinGoal;calorieGoal.value=s.calorieGoal;const t=calculateNutrition();nutritionCalcNote.textContent=`Estimated BMR ${t.bmr.toLocaleString()} kcal · maintenance ${t.tdee.toLocaleString()} kcal. Adjust targets based on energy, recovery and professional advice.`}
function openExercise(i){const x=getLog().exercises[i],id=extractYoutubeId(x.youtube);exerciseDetail.innerHTML=`<p class="eyebrow">EXERCISE GUIDE</p><h2>${escapeHtml(x.name)}</h2>${id?`<div class="video-wrap"><iframe src="https://www.youtube-nocookie.com/embed/${id}?playsinline=1" title="${escapeHtml(x.name)} guide" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`:`<a class="secondary-btn" style="display:block;text-align:center;text-decoration:none" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(x.search||x.name+' proper form')}">Find a free YouTube guide</a>`}<h3>Target</h3><p class="muted">${escapeHtml(x.target||'Custom exercise')}</p><h3>How to perform</h3><p>${escapeHtml(x.instructions||'Use controlled form and stop if you feel sharp pain.')}</p><div class="set-grid"><div class="set-box"><b>${x.sets}</b><small>Sets</small></div><div class="set-box"><b>${x.reps}</b><small>Reps</small></div><div class="set-box"><b>${x.weight||0}</b><small>kg</small></div></div><div class="form-row"><button type="button" class="secondary-btn" id="editExerciseBtn">Edit</button><button type="button" class="primary-btn" id="toggleExerciseDone">${x.done?'Mark incomplete':'Complete exercise'}</button></div><button type="button" class="danger-btn" id="deleteExerciseBtn">Delete from this day</button>`;exerciseDialog.showModal();toggleExerciseDone.onclick=()=>{x.done=!x.done;updateLog({exercises:getLog().exercises});exerciseDialog.close()};editExerciseBtn.onclick=()=>{exerciseDialog.close();openExerciseForm(i)};deleteExerciseBtn.onclick=()=>{if(confirm(`Delete ${x.name} from ${activeDate}?`)){getLog().exercises.splice(i,1);updateLog({exercises:getLog().exercises,planSource:getLog().exercises.length?'custom':'custom-empty'});exerciseDialog.close()}}}
function openExerciseForm(i=null){editingIndex=i;const form=addExerciseForm;form.reset();if(i===null){exerciseFormEyebrow.textContent='NEW EXERCISE';exerciseFormTitle.textContent=`Add to ${activeDate}`;exerciseFormSubmit.textContent='Add exercise';form.sets.value=3;form.reps.value=10;form.weight.value=0}else{const x=getLog().exercises[i];exerciseFormEyebrow.textContent='EDIT EXERCISE';exerciseFormTitle.textContent=x.name;exerciseFormSubmit.textContent='Save changes';for(const k of ['name','sets','reps','weight','target','instructions','youtube'])if(form.elements[k])form.elements[k].value=x[k]??''}addExerciseDialog.showModal()}
function extractYoutubeId(v=''){if(/^[\w-]{11}$/.test(v))return v;try{const u=new URL(v);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1,12);if(u.searchParams.get('v'))return u.searchParams.get('v').slice(0,11);return u.pathname.match(/\/embed\/([\w-]{11})/)?.[1]||''}catch{return''}}
function escapeHtml(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function switchView(id){document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id))}
priorityGrid.onclick=e=>{const b=e.target.closest('[data-priority]');if(!b)return;const l=getLog(),k=b.dataset.priority;if(k==='workout')l.exercises.forEach(x=>x.done=!l.priorities.workout);else l.priorities[k]=!l.priorities[k];saveState();render()};
workoutList.onclick=e=>{const edit=e.target.closest('[data-ex-edit]'),open=e.target.closest('[data-ex-open]');if(edit)openExerciseForm(+edit.dataset.exEdit);else if(open)openExercise(+open.dataset.exOpen);else if(e.target.closest('[data-empty-add]'))openExerciseForm()};workoutList.onchange=e=>{if(e.target.matches('[data-ex-check]')){getLog().exercises[+e.target.dataset.exCheck].done=e.target.checked;updateLog({exercises:getLog().exercises})}};
[['waterInput','water'],['sleepInput','sleep'],['calorieInput','calories'],['proteinInput','protein']].forEach(([id,k])=>document.getElementById(id).addEventListener('change',e=>updateLog({[k]:+e.target.value||0})));memoInput.addEventListener('change',e=>updateLog({memo:e.target.value}));
completeAllBtn.onclick=()=>{const l=getLog();l.exercises.forEach(x=>x.done=true);l.water=state.settings.waterGoal;l.sleep=state.settings.sleepGoal;l.calories=l.calories||state.settings.calorieGoal;l.protein=l.protein||state.settings.proteinGoal;saveState();render()};addExerciseBtn.onclick=()=>openExerciseForm();prevDayBtn.onclick=()=>{activeDate=shiftDate(activeDate,-1);renderToday()};nextDayBtn.onclick=()=>{activeDate=shiftDate(activeDate,1);renderToday()};todayWorkoutBtn.onclick=()=>{activeDate=todayKey();renderToday()};resetPlanBtn.onclick=()=>{if(confirm(`Reset ${activeDate} to the ${weeklyPlan[dateFromKey(activeDate).getDay()].name} plan?`)){getLog().exercises=plannedExercises(activeDate);updateLog({exercises:getLog().exercises,planInitialized:true,planSource:'weekly'})}};
addExerciseForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),item={id:editingIndex===null?crypto.randomUUID():getLog().exercises[editingIndex].id,name:f.get('name'),sets:+f.get('sets'),reps:+f.get('reps'),weight:+f.get('weight'),target:f.get('target'),instructions:f.get('instructions'),youtube:f.get('youtube'),search:f.get('name')+' proper form',done:editingIndex===null?false:getLog().exercises[editingIndex].done};if(editingIndex===null)getLog().exercises.push(item);else getLog().exercises[editingIndex]=item;updateLog({exercises:getLog().exercises,planInitialized:true,planSource:'custom'});addExerciseDialog.close()};
weeklyPlanGrid.onclick=e=>{const b=e.target.closest('[data-open-plan-date]');if(!b)return;activeDate=b.dataset.openPlanDate;switchView('today');renderToday();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));prevMonth.onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()};nextMonth.onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()};calendarGrid.onclick=e=>{const d=e.target.closest('[data-date]');if(d){selectedDate=d.dataset.date;renderCalendar()}};
function saveProfileFromForm(){Object.assign(state.settings,{name:displayName.value.trim()||'Ellen',sex:sexSetting.value,age:+ageSetting.value||37,height:+heightSetting.value||160,currentWeight:+currentWeightSetting.value||78,currentBodyFat:+currentBodyFatSetting.value||'',goalWeight:+goalWeightSetting.value||'',goalMode:goalMode.value,activity:+activitySetting.value||1.55,mealCount:+mealCountSetting.value||4});saveState();render()}
saveProfileBtn.onclick=()=>{saveProfileFromForm();alert('Profile saved.')}
autoNutritionBtn.onclick=()=>{saveProfileFromForm();const t=calculateNutrition();Object.assign(state.settings,{calorieGoal:t.kcal,proteinGoal:t.protein,carbGoal:t.carb,fatGoal:t.fat,waterGoal:t.water});delete getLog(activeDate).mealPlan;saveState();render();alert('Nutrition targets and today\'s meal plan were created.')}
regenerateMealsBtn.onclick=()=>{delete getLog(activeDate).mealPlan;saveState();renderMeals(getLog(activeDate))};
mealPlanList.onclick=e=>{const c=e.target.closest('[data-meal-change]'),d=e.target.closest('[data-meal-done]'),edit=e.target.closest('[data-meal-edit]'),food=e.target.closest('[data-meal-food]'),l=getLog(activeDate),meals=ensureMeals(l,activeDate);if(food){openFoodEditor(+food.dataset.mealFood);return}else if(edit){const m=meals[+edit.dataset.mealEdit],current=m.customText||mealChoices[m.key][m.choice%mealChoices[m.key].length],value=prompt(`${m.name} 식단 메모를 입력하세요.`,current);if(value===null)return;m.customText=value.trim();if(!m.customText)delete m.customText}else if(c){const m=meals[+c.dataset.mealChange];delete m.customText;m.foodItems=[];m.choice=(m.choice+1)%mealChoices[m.key].length}else if(d){meals[+d.dataset.mealDone].done=!meals[+d.dataset.mealDone].done}else return;syncFoodTotals(l,meals);l.priorities.nutrition=meals.every(x=>x.done);saveState();render()}
saveSettingsBtn.onclick=()=>{Object.assign(state.settings,{waterGoal:+waterGoal.value||2000,sleepGoal:+sleepGoal.value||7.5,proteinGoal:+proteinGoal.value||120,calorieGoal:+calorieGoal.value||1800});saveState();render();alert('Targets saved.')};saveBodyBtn.onclick=()=>{state.body=state.body.filter(x=>x.date!==todayKey());state.body.push({date:todayKey(),weight:+weightInput.value||null,bodyFat:+bodyFatInput.value||null,waist:+waistInput.value||null,muscle:+muscleInput.value||null});saveState();alert('Body record saved.')};exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ellens-project-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)};importInput.onchange=async e=>{try{state={...clone(defaults),...JSON.parse(await e.target.files[0].text())};saveState();render();alert('Backup imported.')}catch{alert('That backup file could not be read.')}};celebrationClose.onclick=()=>celebrationDialog.close();profileBtn.onclick=()=>accountDialog.showModal();
async function initSupabase(){const c=window.ELLEN_CONFIG||{},badge=document.getElementById('connectionBadge');if(!c.SUPABASE_URL||!c.SUPABASE_ANON_KEY){syncNowBtn.disabled=true;syncStatus.textContent='Supabase configuration is missing.';return}if(!window.supabase){syncStatus.textContent='Internet connection required.';return}try{supabaseClient=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const{data,error}=await supabaseClient.auth.getSession();if(error)throw error;setUser(data.session?.user||null);supabaseClient.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null))}catch(e){syncStatus.textContent='Cloud connection failed: '+e.message}}
function setUser(user){currentUser=user;authTitle.textContent=user?user.email:'Cloud ready';syncStatus.textContent=user?'Synced just now.':'Supabase is connected. Create an account or sign in.';authFields.hidden=!!user;signOutBtn.hidden=!user;syncNowBtn.disabled=!user;if(user)cloudPull()}
signInBtn.onclick=()=>authAction('signin');signUpBtn.onclick=()=>authAction('signup');signOutBtn.onclick=async()=>{await supabaseClient?.auth.signOut();setUser(null)};syncNowBtn.onclick=()=>cloudSync(true);async function authAction(mode){if(!supabaseClient)return alert('Cloud connection is not ready.');const email=emailInput.value.trim(),password=passwordInput.value;if(!email||password.length<6)return alert('Enter an email and a password with at least 6 characters.');const fn=mode==='signup'?'signUp':'signInWithPassword',r=await supabaseClient.auth[fn]({email,password});if(r.error)alert(r.error.message);else alert(mode==='signup'?'Account created. You can sign in now if email confirmation is disabled.':'Signed in. Cloud sync is active.')}
let syncTimer;function scheduleCloudSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>cloudSync(false),800)}async function cloudSync(show=false){if(!supabaseClient||!currentUser)return;syncStatus.textContent='Syncing…';const rows=Object.entries(state.logs).map(([date,payload])=>({user_id:currentUser.id,date,payload,updated_at:payload.updatedAt||new Date().toISOString()})),{error}=rows.length?await supabaseClient.from('daily_logs').upsert(rows,{onConflict:'user_id,date'}):{error:null};syncStatus.textContent=error?'Sync failed: '+error.message:'Synced just now.';if(show)alert(error?error.message:'Sync complete.')}async function cloudPull(){if(!supabaseClient||!currentUser)return;const{data,error}=await supabaseClient.from('daily_logs').select('date,payload,updated_at').eq('user_id',currentUser.id);if(error){syncStatus.textContent='Could not load cloud data.';return}for(const row of data||[]){const local=state.logs[row.date];if(!local||new Date(row.updated_at)>new Date(local.updatedAt||0))state.logs[row.date]=row.payload}localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();syncStatus.textContent='Cloud data loaded.'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));initSupabase();render();
